name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r ci_cd-flask-app/requirements.txt

    - name: Run tests
      run: |
        cd ci_cd-flask-app
        pytest

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-flask:latest ./ci_cd-flask-app

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-flask:latest

    - name: Trigger Render Deploy
  uses: joel-alejandro/deploy-to-render@v1
  with:
    api_key: ${{ secrets.RENDER_API_KEY }}
    service_id: ${{ secrets.RENDER_SERVICE_ID }}

- name: Run tests
  run: |
    cd ci_cd-flask-app
    pytest -v
